


const stateDefault = {
    mangFilm: [
        {
            "maPhim": 1314,
            "tenPhim": "Gà Trống Nuôi Vợ",
            "biDanh": "ga-trong-nuoi-vo",
            "trailer": "https://youtu.be/IY7ktRwopPw",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/ga-trong-nuoi-vo_gp01.png",
            "moTa": "ghntfhfghfghfghfghfg",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-09T11:38:17.29",
            "danhGia": 10
        },
        {
            "maPhim": 1329,
            "tenPhim": "Bố Già",
            "biDanh": "bo-gia",
            "trailer": "https://www.youtube.com/embed/IHNzOHi8sJs",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/bo-gia_gp01.jpg",
            "moTa": "Tui Chưa Coi Nên Chưa Biết",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-03T20:30:24.247",
            "danhGia": 10
        },
        {
            "maPhim": 1344,
            "tenPhim": "Avenger 1",
            "biDanh": "avenger-1",
            "trailer": "https://www.youtube.com/watch?v=KlFh2oJzbfU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/avenger-1_gp01.jpg",
            "moTa": "iám Mục Bóng Tối (Woo Do Hwan) – tên quỷ Satan đột lốt người. Từ đó sự thật về cái chết của cha Yong Hu cũng dần được hé lộ cũng như nguyên nhân anh trở thành “người được chọn”.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 5
        },
        {
            "maPhim": 1359,
            "tenPhim": "Vợ 3",
            "biDanh": "vo-3",
            "trailer": "https://www.youtube.com/embed/MyqZf8LiWvM",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/vo-ba_gp01.jpg",
            "moTa": "mat hoi lac thoi",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-22T21:09:35.143",
            "danhGia": 10
        },
        {
            "maPhim": 1374,
            "tenPhim": "Natra Two",
            "biDanh": "natra-two",
            "trailer": "https://www.youtube.com/embed/U-MxFzqU3QA",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/natra-two_gp01.jpg",
            "moTa": "ab",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-16T03:12:19.193",
            "danhGia": 10
        },
        {
            "maPhim": 1389,
            "tenPhim": "Diep Van 1",
            "biDanh": "diep-van-1",
            "trailer": "https://www.youtube.com/embed/1HpZevFifuo",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/diep-van_gp01.jpg",
            "moTa": "Mắt hút",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-05T22:16:31.513",
            "danhGia": 10
        },
        {
            "maPhim": 1404,
            "tenPhim": "Mắt biếc",
            "biDanh": "mat-biec",
            "trailer": "https://www.youtube.com/embed/RFinNxS5KN4",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/mat-biec_gp01.png",
            "moTa": "Trứng rán cần mỡ, bắp cần bơ, yêu không cần cớ, cần cậu cơ <3",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2019-07-29T00:00:00",
            "danhGia": 9
        },
        {
            "maPhim": 1419,
            "tenPhim": "Hai đứa trẻ",
            "biDanh": "hai-dua-tre",
            "trailer": "https://www.youtube.com/embed/AAgnQdiZFsQ",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/hai-dua-tre_gp01.png",
            "moTa": "Hai Đứa Trẻ Mồ Côi",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-02-12T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 1434,
            "tenPhim": "Tennet 2",
            "biDanh": "tennet-2",
            "trailer": "https://www.youtube.com/embed/hEJnMQG9ev8",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/abcabc_gp01.png",
            "moTa": "In a stark desert landscape where humanity is broken, two rebels just might be able to restore order: Max, a man of action and of few words, and Furiosa, a woman of action who is looking to make it back to her childhood homeland.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 1449,
            "tenPhim": "True Detective",
            "biDanh": "true-detective",
            "trailer": "https://www.youtube.com/embed/TXwCoNwBSkQ",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/true-detective_gp01.jpeg",
            "moTa": "An anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-04T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 1464,
            "tenPhim": "The Longest Ride",
            "biDanh": "the-longest-ride",
            "trailer": "https://www.youtube.com/embed/FUS_Q7FsfqU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/thelongestride.jpg",
            "moTa": "After an automobile crash, the lives of a young couple intertwine with a much older man, as he reflects back on a past love.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2019-07-29T00:00:00",
            "danhGia": 5
        },
        {
            "maPhim": 1479,
            "tenPhim": "Đẹp gái không có gì sai",
            "biDanh": "dep-gai-khong-co-gi-sai",
            "trailer": "https://www.youtube.com/embed/0M15BMH8K1I",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/dep-gai-khong-co-gi-sai_gp01.png",
            "moTa": "lll",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-23T14:41:47.373",
            "danhGia": 10
        },
        {
            "maPhim": 1494,
            "tenPhim": "Gene",
            "biDanh": "gene",
            "trailer": "https://www.youtube.com/embed/cX-Oqdt7gmc",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/gene_gp01.jpg",
            "moTa": "SpaceSpeaker",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-01-02T00:00:00",
            "danhGia": 4
        },
        {
            "maPhim": 1509,
            "tenPhim": "Specter",
            "biDanh": "specter",
            "trailer": "https://www.youtube.com/embed/LTDaET-JweU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/spectre.jpg",
            "moTa": "A cryptic message from Bond's past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2019-07-29T00:00:00",
            "danhGia": 5
        },
        {
            "maPhim": 1524,
            "tenPhim": "Chuyện Ngày Xưa Ở Hollywood",
            "biDanh": "chuyen-ngay-xua-o-hollywood",
            "trailer": "https://www.youtube.com/embed/NBdkQGFDNXY",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/chuyen-ngay-xua-o-hollywood_gp01.jpg",
            "moTa": "Chuyện Ngày Xưa ở... Hollywood lấy bối cảnh Los Angeles vào năm 1969 với hai nhân vật chính là Rick Dalton - cựu ngôi sao của một bộ phim truyền hình viễn Tây - và người đóng thế lâu năm cho anh là Cliff Booth. ",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2019-08-02T00:00:00",
            "danhGia": 9
        },
        {
            "maPhim": 1539,
            "tenPhim": "Angry Bird 2 ",
            "biDanh": "angry-bird-2",
            "trailer": "https://www.youtube.com/embed/RDj8Y2K0ODA",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/angry-bird-2_gp01.jpg",
            "moTa": "Angry Birds 2 tiếp tục kể về âm mưu trả thù Angry Birds sau cuộc đại chiến giành lại trứng ở Angry Birds 1 của Vua Lợn. Thế nhưng cuối cùng cả hai lại phải bắt tay hợp tác để chống lại nữ hoàng băng giá Zeta. Kẻ đã dùng đại bác phá hủy đảo Heo và đảo Chim, khiến cư dân của hai hòn đảo bỏ chạy toán loạn.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2025-11-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 2528,
            "tenPhim": "Mắt Biếc",
            "biDanh": "mat-biec",
            "trailer": "https://www.youtube.com/embed/KSFS0OfIK2c",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/mat-biec_gp01.jpg",
            "moTa": "Mắt biếc (tựa tiếng Anh: Dreamy Eyes) là một phim điện ảnh Việt Nam do Victor Vũ đạo diễn[2], chuyển thể từ truyện dài cùng tên của nhà văn Nguyễn Nhật Ánh[3]. Phim ra mắt vào ngày 20 tháng 12 năm 2019. Đây là bộ phim thứ hai của Victor Vũ đạo diễn dựa trên truyện dài của Nguyễn Nhật Ánh sau thành công từ phim Tôi thấy hoa vàng trên cỏ xanh năm 2015.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-03-14T00:00:00",
            "danhGia": 5
        },
        {
            "maPhim": 2532,
            "tenPhim": "Egg cần mỡ",
            "biDanh": "egg-can-mo",
            "trailer": "https://www.youtube.com/embed/uMnaJxLNljM",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/egg-can-mo_gp01.jpg",
            "moTa": "Trứng rán cần mỡ (cười duyên) bắp cần bơ yêu không cần cớ (cắn lưỡi) cần cậu cơ",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-07-11T00:00:00",
            "danhGia": 4
        },
        {
            "maPhim": 2598,
            "tenPhim": "DragonBall",
            "biDanh": "dragonball",
            "trailer": "https://www.youtube.com/embed/FHgm89hKpXU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/dragonball_gp01.jpg",
            "moTa": "Son Goku",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-03-14T00:00:00",
            "danhGia": 2
        },
        {
            "maPhim": 2602,
            "tenPhim": "Chuyến tàu may mắn",
            "biDanh": "chuyen-tau-may-man",
            "trailer": "https://www.youtube.com/embed/uC9qU3X1JgM",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/chuyen-tau-may-man_gp01.jpg",
            "moTa": "1234",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-16T04:09:38.81",
            "danhGia": 10
        },
        {
            "maPhim": 2603,
            "tenPhim": "Cô bé nhăn nhó",
            "biDanh": "co-be-nhan-nho",
            "trailer": "https://www.youtube.com/embed/78ngg0SRlEI",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/cao-cau-bay-gio-o-do-ma-edit-phim-to-di_gp01.jpg",
            "moTa": "Dài quá ghi ngắn thôi, tràn hết cả data.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-03T20:31:55.517",
            "danhGia": 10
        },
        {
            "maPhim": 2772,
            "tenPhim": "Natra 5",
            "biDanh": "natra-5",
            "trailer": "https://www.youtube.com/watch?v=5eoxDDWUBNQ",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/thuong_gp01.png",
            "moTa": "djdhkdjhkjd",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 2795,
            "tenPhim": "Dau pha thuong khung",
            "biDanh": "dau-pha-thuong-khung",
            "trailer": "https://www.youtube.com/embed/S3AVcCggRnU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/dau-pha-thuong-khung_gp01.jpg",
            "moTa": "Dau pha thuong khung",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-05-16T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 2803,
            "tenPhim": "Wonder woman 1984",
            "biDanh": "wonder-woman-1984",
            "trailer": "https://youtu.be/sfM7_JLk-84",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/wonder-woman-1984_gp01.jpg",
            "moTa": "Lấy bối cảnh thời kỳ Chiến tranh Lạnh, Wonder Woman 1984 sẽ xoay quanh cuộc đối đầu giữa Nữ thần Chiến binh và Yêu nữ Báo đốm Cheetah.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-08-14T00:00:00",
            "danhGia": 8
        },
        {
            "maPhim": 2854,
            "tenPhim": "Tan dat  ky tru vuong",
            "biDanh": "tan-dat-ky-tru-vuong",
            "trailer": "https://www.youtube.com/watch?v=AntcyqJ6brc",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tan-dat-ky-tru-vuong_gp01.jpg",
            "moTa": "jgrkfjggjrf",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-05-01T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 2864,
            "tenPhim": "Transformers",
            "biDanh": "transformers",
            "trailer": "https://www.youtube.com/watch?v=AntcyqJ6brc",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/transformers_gp01.png",
            "moTa": "Cách đây chừng 4 triệu năm, trên hành tinh Cybertron xa xôi tồn tại một nền văn minh của robot. nhưng rồi nền văn minh ấy bị tàn phá bởi cuộc chiến kéo dài nhiều thế kỷ giữa hai chủng người máy: autobot (phe thiện) và deception (phe ác). Chúng đánh nhau để tranh giành allspark (thực thể lập phương) – thứ có khả năng mang tới quyền lực tối thượng cho kẻ sở hữu nó. ",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-04-20T00:00:00",
            "danhGia": 8
        },
        {
            "maPhim": 3394,
            "tenPhim": "Cuộc sống Mông Cổ",
            "biDanh": "cuoc-song-mong-co",
            "trailer": "string",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/cuoc-song-mong-co_gp01.jpg",
            "moTa": "stringdsdsdsdsd",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4031,
            "tenPhim": "Japan",
            "biDanh": "japan",
            "trailer": "TEST",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/japan_gp01.jpg",
            "moTa": "test",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4284,
            "tenPhim": "Avenger 2",
            "biDanh": "avenger-2",
            "trailer": "https://www.youtube.com/watch?v=ZM719KtmKzs",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/avenger-t-u-2_gp01.jpg",
            "moTa": "king of rap",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-23T14:42:10.747",
            "danhGia": 10
        },
        {
            "maPhim": 4329,
            "tenPhim": "Thép đã tôi thê đấy",
            "biDanh": "thep-da-toi-the-day",
            "trailer": "https://www.youtube.com/watch?v=p25V4fypHmg",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/thep-da-toi-the-day_gp01.jpg",
            "moTa": "Chào mừng bạn đến với tab nội dung đang theo dõi mới! Khám phá ý tưởng từ những người bạn theo dõi...",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-12-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4332,
            "tenPhim": "Naruto",
            "biDanh": "naruto",
            "trailer": "https://www.youtube.com/embed/leshlejZaAE",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/naruto_gp01.jpg",
            "moTa": "ICD quán quân không nói nhiều",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4428,
            "tenPhim": "Sky Toura",
            "biDanh": "sky-toura",
            "trailer": "https://www.youtube.com/embed/t7m1iqs_b-U",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/sky-toura_gp01.jpg",
            "moTa": "Lần đầu tiên tại Việt Naam, một nghệ sĩ phát hành bộ phim tài liệu âm nhạc về tour diễn của mình trên màn ảnh rộng. Bộ phim hứa hẹn sẽ đem đến cho khán giả những khoảnh khắc đẹp đẽ nhất về sự kiện âm nhạc đình đám nhất năm 2019, khi Sơn Tùng M-TP hết mình cùng hàng nghìn người hâm mộ trong âm nhạc và cả những cảnh hậu trường ghi lại toàn bộ quá trình chuẩn bị và sản xuất SKY TOUR.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-06-12T00:00:00",
            "danhGia": 8
        },
        {
            "maPhim": 4430,
            "tenPhim": "Chị Mười Ba",
            "biDanh": "chi-muoi-ba",
            "trailer": "https://www.youtube.com/embed/zxvHV58lp6s",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/chi-muoi-ba_gp01.jpg",
            "moTa": "Chị Mười Ba đưa Kẽm Gai, tay đàn em cũ vừa mới ra tù, lên Đà Lạt để làm việc cho tiệm Gara của mình. Tại đây, Kẽm Gai dường như đã tìm lại được sự bình yên và hạnh phúc. Tuy vậy, anh sớm trở thành đối tượng bị tình nghi giết hại Đức Mát - em trai của đại ca Thắng Khùng khét tiếng đất Đà Lạt - và phải trốn chạy.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-11-01T14:54:02.07",
            "danhGia": 10
        },
        {
            "maPhim": 4431,
            "tenPhim": "Vượt Qua Sóng Gió ",
            "biDanh": "vuot-qua-song-gio",
            "trailer": "https://www.youtube.com/embed/1HpZevFifuo",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/vuot-qua-song-gio_gp01.jpg",
            "moTa": "HKT vượt qua sóng gió là bộ phim nói về vieecjj nhóm nhạc abcxyz",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4467,
            "tenPhim": "Lướt Sóng",
            "biDanh": "luot-song",
            "trailer": "https://www.youtube.com/embed/1HpZevFifuo",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/luot-song_gp01.jpg",
            "moTa": "phim thầy kể về một người thầy vui tính",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4468,
            "tenPhim": "Một Ngày An Lành",
            "biDanh": "mot-ngay-an-lanh",
            "trailer": "https://www.youtube.com/watch?v=p25V4fypHmg",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/mot-ngay-an-lanh_gp01.jpg",
            "moTa": "phim người thầy",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-16T03:30:43.907",
            "danhGia": 10
        },
        {
            "maPhim": 4517,
            "tenPhim": "day la gap bơ",
            "biDanh": "day-la-gap-bo",
            "trailer": "https://www.youtube.com/embed/dyuUk_gMRkc",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/my-shunshine_gp01.jpg",
            "moTa": "okkkkkkkkkkkkkp",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4552,
            "tenPhim": "RapViet",
            "biDanh": "rapviet",
            "trailer": "",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/rapviet_gp01.jpg",
            "moTa": "Đây là Rap Việt",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-11-17T19:54:52.82",
            "danhGia": 10
        },
        {
            "maPhim": 4592,
            "tenPhim": "Hãy Trao Cho Anh",
            "biDanh": "hay-trao-cho-anh",
            "trailer": "https://youtu.be/knW7-x7Y7RE",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/hay-trao-cho-anh_gp01.jpg",
            "moTa": "",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4643,
            "tenPhim": "Ròm 2020",
            "biDanh": "rom-2020",
            "trailer": "https://www.youtube.com/watch?v=XRm1P7oGpMQ",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/rom-2020_gp01.jpg",
            "moTa": "Lấy bối cảnh một khu chung cư cũ đang chờ giải tỏa tại Sài Gòn, Ròm kể câu chuyện về cuộc sống của những người dân lao động nơi đây. Họ đều chơi số đề với hy vọng kiếm được một khoản tiền lớn để đổi đời. Ròm là cậu bé làm “cò đề” để kiếm sống qua ngày, chuyên tư vấn cho người dân những con số may mắn để họ có cơ may trúng đề.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-11-20T00:00:00",
            "danhGia": 8
        },
        {
            "maPhim": 4665,
            "tenPhim": "Avatar 2",
            "biDanh": "avatar-2",
            "trailer": "https://www.youtube.com/embed/M8Mi0elohJw",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/avatar-2_gp01.jpg",
            "moTa": "Avatar 2 là bộ phim khoa học viễn tưởng sắp ra mắt của Mỹ do James Cameron đạo diễn và 20th Century Studios sản xuất. Đây là bộ phim thứ hai trong loạt phim Avatar, sau Avatar.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-01-01T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4666,
            "tenPhim": "Joker",
            "biDanh": "joker",
            "trailer": "https://www.youtube.com/embed/zAGVQLHvwOY",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/joker_gp01.jpg",
            "moTa": "Joker là một bộ phim điện ảnh giật gân tâm lý của Mỹ được ra mắt vào năm 2019 dựa trên nhân vật cùng tên của DC Comics. Đây là bộ phim đầu tiên trong loạt phim dựa trên DC Comics mà không thuộc trong DC Extended Universe. Bộ phim được phát hành bởi Warner Bros.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-02-23T10:34:49.503",
            "danhGia": 10
        },
        {
            "maPhim": 4667,
            "tenPhim": "Wanted",
            "biDanh": "wanted",
            "trailer": "https://www.youtube.com/watch?v=edpEspHOeVU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/wanted_gp01.jpg",
            "moTa": "Wanted is a 2008 American action thriller film directed by Timur Bekmambetov and written by Michael Brandt, Derek Haas, and Chris Morgan, loosely based on the comic book miniseries by Mark Millar and J. G. Jones. The film stars James McAvoy, Morgan Freeman, Terence Stamp, Thomas Kretschmann, Common, and Angelina Jolie.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4668,
            "tenPhim": "Vệ Sĩ Sát Thủ: The Hitman's Bodyguard",
            "biDanh": "ve-si-sat-thu-the-hitman-s-bodyguard",
            "trailer": "https://www.youtube.com/embed/uiYbbPpobUs",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/ve-si-sat-thu-the-hitman-s-bodyguard_gp01.jpg",
            "moTa": "Ryan Reynolds sẽ thủ vai một chuyên gia bảo vệ, được đánh giá hạng AAA còn Samuel Jackson thì hóa thân nhân vật sát thủ bị săn lùng nhất thế giới. Hai người, như hai kẻ không đội trời chung, nhưng lại bị ép phải “bảo vệ” nhau trong suốt 24 giờ. Thật trớ trêu khi một sát thủ “khét tiếng” mà cũng có lúc cần đến vệ sĩ riêng. Và trên hành trình đồng hành từ Anh đến Hague, họ sẽ phải đối mặt và “xử lý” rất nhiều tình huống nguy hiểm hay sự truy đuổi của nhiều nhóm khác nhau.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4893,
            "tenPhim": "Tenet",
            "biDanh": "tenet",
            "trailer": "https://www.youtube.com/embed/L3pk_TBkihU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tenet_gp01.jpg",
            "moTa": "Tenet là một bộ phim hành động - giật gân và khoa học viễn tưởng phát hành năm 2020 của Mỹ, do Christopher Nolan đạo diễn kiêm biên kịch. Phim có sự tham gia của John David Washington, Robert Pattinson, Elizabeth Debicki, Dimple Kapadia, Michael Caine, cùng Kenneth Branagh.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-12-17T15:13:45.953",
            "danhGia": 10
        },
        {
            "maPhim": 4956,
            "tenPhim": "Biệt đội diệt quỷ: Gretel & Hansel",
            "biDanh": "biet-doi-diet-quy-gretel-hansel",
            "trailer": "https://www.youtube.com/embed/QZblQLhKcZQ",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/biet-doi-diet-quy-gretel-hansel_gp01.jpg",
            "moTa": "Gretel & Hansel là một bộ phim kinh dị giả tưởng đen tối năm 2020 dựa trên câu chuyện dân gian Đức \"Hansel và Gretel\" của Anh em nhà Grimm. Phim do Oz Perkins đạo diễn, Fred Berger, Brian Kavanaugh-Jones và Dan Kagan sản xuất, với kịch bản của Rob Hayes.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 4972,
            "tenPhim": "Bác sĩ Dolittle: Chuyến phiêu lưu thần thoại",
            "biDanh": "bac-si-dolittle-chuyen-phieu-luu-than-thoai",
            "trailer": "https://www.youtube.com/embed/JzDpEdkWBCg",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/bac-si-dolittle-chuyen-phieu-luu-than-thoai_gp01.jpg",
            "moTa": "Dolittle là một bộ phim Mỹ năm 2020 có yếu tố giả tưởng và phiêu lưu của đạo diễn Stephen Gaghan, từ một kịch bản của Gaghan, Dan Gregor, Doug Mand và Chris McKay và một câu chuyện của Thomas Shepherd.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-12-17T14:37:27.087",
            "danhGia": 10
        },
        {
            "maPhim": 4987,
            "tenPhim": "Hobbs and Shaw",
            "biDanh": "hobbs-and-shaw",
            "trailer": "https://www.youtube.com/embed/b736ZM_KfEk",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/hobbs-and-shaw_gp01.jpg",
            "moTa": "Phim này max hay! luon",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-02-12T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5029,
            "tenPhim": "Nữ Thần Chiến Binh 1984 - Wonder Woman 1984",
            "biDanh": "nu-than-chien-binh-1984-wonder-woman-1984",
            "trailer": "https://www.youtube.com/embed/Vk-gqL3c5qU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/nu-than-chien-binh-1984-wonder-woman-1984_gp01.png",
            "moTa": "Lấy bối cảnh thời kỳ Chiến tranh Lạnh, Wonder Woman 1984 sẽ xoay quanh cuộc đối đầu giữa Nữ thần Chiến binh và Yêu nữ Báo đốm Cheetah.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-01-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5030,
            "tenPhim": "Hoa Phong Nguyệt Vũ - The Crawler",
            "biDanh": "hoa-phong-nguyet-vu-the-crawler",
            "trailer": "https://www.youtube.com/watch?v=IoyYAaORRrw&feature=emb_logo",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/hoa-phong-nguyet-vu-the-crawler_gp01.png",
            "moTa": "Một chuyên viên khai vấn tâm lý đi tìm manh mối về cái chết của nữ khách hàng và đối diện với những thế lực kì bí đang che giấu một bí mật liên quan đến gia đình anh ta.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-12-04T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5031,
            "tenPhim": "Gia Đình Croods: Kỷ Nguyên Mới - The Croods: New Age",
            "biDanh": "gia-dinh-croods-ky-nguyen-moi-the-croods-new-age",
            "trailer": "https://www.youtube.com/watch?v=0qaStyeKpLo&feature=emb_logo",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/gia-dinh-croods-ky-nguyen-moi-the-croods-new-age_gp01.png",
            "moTa": "Sinh tồn trong một thế giới tiền sử luôn rình rập hiểm nguy từ đủ loài quái thú hung dữ cho tới thảm họa ngày tận thế, Nhà Croods chưa từng một lần chùn bước. Nhưng giờ đây họ sẽ phải đối mặt với thử thách lớn nhất từ trước tới nay: chung sống với một gia đình khác. Để tìm kiếm một mái nhà an toàn hơn, Nhà Croods bắt đầu hành trình khám phá thế giới tiến tới những vùng đất xa xôi đầy tiềm năng. Một ngày nọ, họ tình cờ lạc vào một nơi yên bình có đầy đủ mọi tiện nghi hiện đại và biệt lập với tường vây bao quanh. Tưởng rằng mọi vấn đề trong cuộc sống sẽ được giải quyết thì Nhà Croods lại phải chấp nhận với sự thật rằng đã có một gia đình khác định cư ở đây đó chính là Nhà Bettermans.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-01-15T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5032,
            "tenPhim": "Cuộc Chiến Hủy Diệt - Skylines",
            "biDanh": "cuoc-chien-huy-diet-skylines",
            "trailer": "https://www.youtube.com/watch?v=mFgmcsRzvOo",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/cuoc-chien-huy-diet-skylines_gp01.png",
            "moTa": "Khi một loại virus đe dọa biến những người ngoài hành tinh thân thiện đang sinh sống trên trái đất chống lại con người, Đội trưởng Rose Corley phải lãnh đạo một đội lính đánh thuê ưu tú đến thế giới ngoài hành tinh để cứu những gì còn lại của nhân loại",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-01-23T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5044,
            "tenPhim": "Birds of Prey: Cuộc lột xác huy hoàng của Harley Quinn",
            "biDanh": "birds-of-prey-cuoc-lot-xac-huy-hoang-cua-harley-quinn",
            "trailer": "https://www.youtube.com/embed/kGM4uYZzfu0",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/birds-of-prey-cuoc-lot-xac-huy-hoang-cua-harley-quinn_gp01.jpeg",
            "moTa": "Birds of prey là một bộ phim siêu anh hùng năm 2020 của Mỹ. Đây là bộ phim thứ tám trong Vũ trụ Mở rộng DC do Cathy Yan đạo diễn, dựa trên kịch bản của Christina Hodson",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-12-23T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5104,
            "tenPhim": "How To Train Your Dragon",
            "biDanh": "how-to-train-your-dragon",
            "trailer": "https://youtu.be/oKiYuIsPxYk",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/how-to-train-your-dragon_gp01.jpg",
            "moTa": "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-05-01T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5125,
            "tenPhim": "Người Cần Quên Phải Nhớ",
            "biDanh": "nguoi-can-quen-phai-nho",
            "trailer": "https://www.youtube.com/embed/RfLnQkiD3iQ",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/nguoi-can-quen-phai-nho_gp01.png",
            "moTa": "Người Cần Quên Phải Nhớ xoay quanh Loan, một nữ phóng viên năng động và nhạy bén. Nghi ngờ cái chết đột ngột của cha mình, cô quyết tâm sử dụng kiến thức nghiệp vụ nhằm vén màn bí mật bằng mọi giá. Trên hành trình “phá án”, Loan đã vô ý khiến Bình, gã giang hồ tưởng ngầu mà dễ mến bị chấn thương rồi mất trí nhớ. Trải qua hàng loạt tình huống dở khóc dở cười, hai người họ dần nảy sinh tình cảm với nhau.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-12-01T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5126,
            "tenPhim": "Cuộc sống nhiệm màu - Soul",
            "biDanh": "cuoc-song-nhiem-mau-soul",
            "trailer": "https://www.youtube.com/embed/D6zVlPKn2AI",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/cuoc-song-nhiem-mau-soul_gp01.jpeg",
            "moTa": "Mỗi con người đều có một linh hồn trú ngụ, vậy tại sao linh hồn này lại chọn chúng ta? Điều gì khiến bạn là chính bạn?",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-16T23:38:14.793",
            "danhGia": 10
        },
        {
            "maPhim": 5163,
            "tenPhim": "Thợ Săn Quái Vật - Monster Hunter",
            "biDanh": "tho-san-quai-vat-monster-hunter",
            "trailer": "https://www.youtube.com/embed/puQyZsaTtqY",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tho-san-quai-vat-monster-hunter_gp01.png",
            "moTa": "Monster Hunter được chuyển thể từ series game nổi tiếng cùng tên của Capcom. Trong phim, đội trưởng Artemis của nữ diễn viên Milla Jovovich (Resident Evil) và đồng đội đã vô tình bước qua một cánh cửa bí ẩn dẫn tới thế giới khác. Tại đây, họ phải chiến đấu với nhiều loài quái vật khổng lồ trong hành trình trở về thế giới. Đồng hành với họ trong trận chiến là nhân vật “Thợ săn” của nam diễn viên Tony Jaa (Ong Bak). Monster Hunter hứa hẹn sẽ là bom tấn hành động với những màn săn quái vật khổng lồ hoành tráng nhất năm 2020.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-12-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5178,
            "tenPhim": "Josée, Nàng Thơ Của Tôi - Josée",
            "biDanh": "josee-nang-tho-cua-toi-josee",
            "trailer": "https://www.youtube.com/embed/PqNGHKLyPD0",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/josee-nang-tho-cua-toi-josee_gp01.png",
            "moTa": "Bộ phim là câu chuyện tình nên thơ của cậu sinh viên Young Seok (Nam Joo Hyuk) và Josée (Han Ji Min), một cô gái khuyết tật phải ngồi xe lăn vào mùa đông lạnh lẽo. Cuộc gặp gỡ đã khiến thế giới của Josée thay đổi.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-02-25T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5200,
            "tenPhim": "Võ Sinh Đại Chiến",
            "biDanh": "vo-sinh-dai-chien",
            "trailer": "https://www.youtube.com/embed/mrNqbx4vUvA",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/vo-sinh-dai-chien_gp01.png",
            "moTa": "Phim kể về “sự nghiệp” giải ngố của anh chàng Khoa từ Bình Định vào Sài Gòn nhập học. Thích võ thuật từ nhỏ, chân ướt chân ráo vào câu lạc bộ võ Ta của trường và phải lòng ngay “tiểu thư” danh giá của bao chàng theo đuổi.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-01-01T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5240,
            "tenPhim": "a lonely person",
            "biDanh": "a-lonely-person",
            "trailer": "https://www.youtube.com/embed/UMXATImg6e4",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/a-lonely-person_gp01.jpg",
            "moTa": "Đây là bộ phim có thật !",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-01-17T00:52:09.613",
            "danhGia": 10
        },
        {
            "maPhim": 5646,
            "tenPhim": "Iron-man",
            "biDanh": "iron-man",
            "trailer": "https://www.youtube.com/watch?v=8hYlB38asDY",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/iron-man_gp01.jpeg",
            "moTa": "Iron-man",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-02-21T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5648,
            "tenPhim": "lao gia ",
            "biDanh": "lao-gia",
            "trailer": "giagiagia",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/lao-gia_gp01.png",
            "moTa": "lao gia va con cho",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-17T06:48:11.68",
            "danhGia": 10
        },
        {
            "maPhim": 5654,
            "tenPhim": "Big Hotel",
            "biDanh": "big-hotel",
            "trailer": "ssssssssssss",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/big-hotel_gp01.jpg",
            "moTa": "ssssssssssss",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5655,
            "tenPhim": "rich",
            "biDanh": "rich",
            "trailer": "asdfasdf",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/rich_gp01.jpg",
            "moTa": "asdfasdfa",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-12-20T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5659,
            "tenPhim": "abcv",
            "biDanh": "abcv",
            "trailer": "youtuber",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/abcv_gp01.jpg",
            "moTa": "haha",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5687,
            "tenPhim": "kkk",
            "biDanh": "kkk",
            "trailer": "kkk",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/kkk_gp01.jpg",
            "moTa": "kkk",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-02-15T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5748,
            "tenPhim": "Vợ ba",
            "biDanh": "vo-ba",
            "trailer": "vo-ba",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/vo-ba_gp01.jpg",
            "moTa": "Vợ ba đánh ba vợ",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-02-26T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5796,
            "tenPhim": "avatar",
            "biDanh": "avatar",
            "trailer": "https://www.youtube.com/watch?v=6ziBFh3V1aM",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/avatar_gp01.jpg",
            "moTa": "hay lắm mọi ng ơi",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-01-01T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5914,
            "tenPhim": "vvvvvtttt",
            "biDanh": "vvvvvtttt",
            "trailer": "vvvvv",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/vvvvvtttt_gp01.png",
            "moTa": "vvvvvttt",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-13T00:00:00",
            "danhGia": 12
        },
        {
            "maPhim": 5918,
            "tenPhim": "Death Stranding",
            "biDanh": "death-stranding",
            "trailer": "https://www.youtube.com/embed/tCI396HyhbQ",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/death-stranding_gp01.jpg",
            "moTa": "From legendary game creator Hideo Kojima comes an all-new, genre-defying experience. Sam Bridges must brave a world utterly transformed by the Death Stranding. Carrying the disconnected remnants of our future in his hands, he embarks on a journey to reconnect the shattered world one step at a time.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-01T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5930,
            "tenPhim": "phimmoi khong sap",
            "biDanh": "phimmoi-khong-sap",
            "trailer": "trailer hay",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/phimmoi-khong-sap_gp01.jpg",
            "moTa": "motataaa",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-17T06:47:00.96",
            "danhGia": 10
        },
        {
            "maPhim": 5964,
            "tenPhim": "Red dead redemtion 2",
            "biDanh": "red-dead-redemtion-2",
            "trailer": "https://www.youtube.com/embed/gmA6MrX81z4",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/red-dead-redemtion-2_gp01.jpg",
            "moTa": "Red Dead Redemption 2[a] là một trò chơi hành động-phiêu lưu thuộc chủ đề cao bồi viễn Tây với góc nhìn thứ nhất và thứ ba, được phát triển bởi Rockstar Studios và xuất bản bởi Rockstar Games, phát hành vào ngày 26 tháng 10 năm 2018 cho PlayStation 4 và Xbox One và dự kiến phát hành vào tháng 11 năm 2019 cho Google Stadia và Microsoft Windows. Là trò chơi thứ ba trong sêri Red Dead, tiền truyện (chi tiết xem hậu truyện) và là phần hai của Red Dead Redemption. Đặt bối cảnh hư cấu quay về năm 1899 tại miền viễn Tây Hoa Kỳ, câu chuyện xoay quanh về kẻ ngoài vòng pháp luật Arthur Morgan, một thành viên của băng đảng Van der Line với kẻ đứng đầu là Dutch. Cả băng cố gắng đối phó với sự suy tàn của miền Tây hoang dã và chống lại chính quyền, cùng nhiều đối thủ khác. Câu chuyện cũng theo sau John Marston, nhân vật chính đến từ Red Dead Redemption.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2018-01-01T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5967,
            "tenPhim": "bố già",
            "biDanh": "bo-gia",
            "trailer": "https://www.youtube.com/embed/jluSu8Rw6YE",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/bo-gia_gp01.jpg",
            "moTa": "nghe đồn phim hay lắm đi xem đi",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-17T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 5984,
            "tenPhim": "dgefge",
            "biDanh": "dgefge",
            "trailer": "gfhgfgf",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/dgefge_gp01.jfif",
            "moTa": "vvvvvv",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-27T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6018,
            "tenPhim": "hành tinh hỗn loạn",
            "biDanh": "hanh-tinh-hon-loan",
            "trailer": "sdasda",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/hanh-tinh-hon-loan_gp01.jpg",
            "moTa": "con gà có trước hay quả trứng có trước",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-10-02T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6019,
            "tenPhim": "palm spring",
            "biDanh": "palm-spring",
            "trailer": "dsasd",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/palm-spring_gp01.jpg",
            "moTa": "ni hao ma??",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-10-02T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6023,
            "tenPhim": "Justice Luege",
            "biDanh": "justice-luege",
            "trailer": "https://www.youtube.com/embed/ZrdQSAX2kyw",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/justice-luege_gp01.jpg",
            "moTa": "RestoreSnyderCut",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-22T20:07:26.357",
            "danhGia": 10
        },
        {
            "maPhim": 6029,
            "tenPhim": "Con Bò Xanh",
            "biDanh": "con-bo-xanh",
            "trailer": "https://www.youtube.com/embed/vOXZkm9p_zY",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/con-bo-cuoi_gp01.png",
            "moTa": "Con Bò Cười",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-23T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6052,
            "tenPhim": "Neko",
            "biDanh": "neko",
            "trailer": "https://www.youtube.com/embed/lLlurMAvcKw",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/neko_gp01.jpg",
            "moTa": "abc xyz",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-12-22T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6054,
            "tenPhim": "How To Become Wjbu",
            "biDanh": "how-to-become-wjbu",
            "trailer": "https://www.youtube.com/embed/PQFWKClEw1g?list=RDPQFWKClEw1g",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/how-to-become-wjbu_gp01.jpg",
            "moTa": "Học cách làm wjbu",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-27T14:55:00.827",
            "danhGia": 10
        },
        {
            "maPhim": 6064,
            "tenPhim": "test959",
            "biDanh": "test959",
            "trailer": "test959",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/test959_gp01.jpg",
            "moTa": "test959",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6077,
            "tenPhim": "death Stranding",
            "biDanh": "death-stranding",
            "trailer": "https://www.youtube.com/embed/tCI396HyhbQ",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/death-stranding_gp01.jpg",
            "moTa": "From legendary game creator Hideo Kojima comes an all-new, genre-defying experience. Sam Bridges must brave a world utterly transformed by the Death Stranding. Carrying the disconnected remnants of our future in his hands, he embarks on a journey to reconnect the shattered world one step at a time.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2022-02-07T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6088,
            "tenPhim": "KT",
            "biDanh": "kt",
            "trailer": "https://youtu.be/IY7ktRwopPw",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/kt_gp01.jpg",
            "moTa": "So Easy",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-01-11T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6098,
            "tenPhim": " Bố Giá Victor 2",
            "biDanh": "bo-gia-victor-2",
            "trailer": "https://youtu.be/uVa1lTvmVhs",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/bo-gia-victor-2_gp01.jpg",
            "moTa": "Phim sẽ xoay quanh lối sống thường nhật của một xóm lao động nghèo, ở đó có bộ tứ anh em Giàu - Sang - Phú - Quý với Ba Sang sẽ là nhân vật chính, hay lo chuyện bao đồng nhưng vô cùng thương con cái. Câu chuyện phim tập trung về hai cha con Ba Sang (Trấn Thành) và Quắn (Tuấn Trần). Dù yêu thương nhau nhưng khoảng cách thế hệ đã đem đến những bất đồng lớn giữa hai cha con. Liệu cả hai có thể cho nhau cơ hội thấu hiểu đối phương, thu hẹp khoảng cách và tạo nên hạnh phúc từ sự khác biệt?",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-06T21:37:38.47",
            "danhGia": 10
        },
        {
            "maPhim": 6099,
            "tenPhim": "Kong vs godzilla",
            "biDanh": "kong-vs-godzilla",
            "trailer": "https://www.youtube.com/watch?v=P6HqTjuZPAk&ab_channel=FilmSelectTrailer",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/kong-vs-godzilla_gp01.jpg",
            "moTa": "adsadasd",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-13T00:00:00",
            "danhGia": 9
        },
        {
            "maPhim": 6113,
            "tenPhim": "LẬT MẶT 48H",
            "biDanh": "lat-mat-48h",
            "trailer": "https://youtu.be/qu5xNg4MQ5Q",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/lat-mat-48h_gp01.PNG",
            "moTa": "Lý Hải trở lại với dòng phim hành động sở trường của mình. Bối cảnh hoành tráng với sự đầu tư nghiêm túc, siêu phẩm hành động Việt Lật Mặt 48h sẽ kể về một hành trình trốn chạy đầy kịch tính, nghẹt thở đến phút cuối cùng.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-16T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6117,
            "tenPhim": "What's wrong with secretary kim 2",
            "biDanh": "what-s-wrong-with-secretary-kim-2",
            "trailer": "https://youtu.be/uVa1lTvmVhs",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/what-s-wrong-with-secretary-kim-2_gp01.PNG",
            "moTa": "What's Wrong with Secretary Kim? is a 2018 South Korean television series starring Park Seo-joon and Park Min-young. It is based on the novel of the same title by Jung Kyung-yoon which was first published in 2013, which was then serialized into a comic in 2015 via KakaoPage. The series aired on tvN from June 6 to July 26, 2018, on Wednesdays and Thursdays for 16 episodes.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-21T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6123,
            "tenPhim": "Tom & Jerry",
            "biDanh": "tom-jerry",
            "trailer": "https://www.youtube.com/watch?v=kP9TfCWaQT4",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tom-jerry_gp01.png",
            "moTa": "Tom & Jerry Battle",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6124,
            "tenPhim": "Tom & Jerry",
            "biDanh": "tom-jerry",
            "trailer": "https://youtu.be/fgqEyC19538",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tom-jerry_gp01.jpg",
            "moTa": "Tom & Jerry",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6131,
            "tenPhim": "yassua",
            "biDanh": "yassua",
            "trailer": "https://www.youtube.com/watch?v=sot5R1UUtQI",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/yassua_gp01.jpg",
            "moTa": "hasagi",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6132,
            "tenPhim": "Fight for my way",
            "biDanh": "fight-for-my-way",
            "trailer": "https://www.youtube.com/embed/9l5KoxFqQZY",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/fight-for-my-way_gp01.jpg",
            "moTa": "Khi hai kẻ thù truyền kiếp gặp nhau trong một trận chiến ngoạn mục, số phận của cả thế giới vẫn còn bị bỏ ngỏ… Bị đưa khỏi Đảo Đầu Lâu, Kong cùng Jia, một cô bé mồ côi có mối liên kết mạnh mẽ với mình và đội bảo vệ đặc biệt hướng về mái nhà mới. Bất ngờ, nhóm đụng độ phải Godzilla hùng mạnh, tạo ra một làn sóng hủy diệt trên toàn cầu. Thực chất, cuộc chiến giữa hai kẻ khổng lồ dưới sự thao túng của các thế lực vô hình mới chỉ là điểm khởi đầu để khám phá những bí ẩn nằm sâu trong tâm Trái đất.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-03-21T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6133,
            "tenPhim": "Tom & Jerry",
            "biDanh": "tom-jerry",
            "trailer": "https://www.youtube.com/watch?v=kP9TfCWaQT4&ab_channel=WarnerBros.Pictures",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tom-jerry_gp01.jpg",
            "moTa": "abcxyz",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6134,
            "tenPhim": "Tom & Jerry",
            "biDanh": "tom-jerry",
            "trailer": "https://www.youtube.com/watch?v=kP9TfCWaQT4&ab_channel=WarnerBros.Pictures",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tom-jerry_gp01.jpg",
            "moTa": "abcxyz",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6135,
            "tenPhim": "Tom & Jerry",
            "biDanh": "tom-jerry",
            "trailer": "https://www.youtube.com/watch?v=kP9TfCWaQT4&ab_channel=WarnerBros.Pictures",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tom-jerry_gp01.jpg",
            "moTa": "abcxyz",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6143,
            "tenPhim": "Tom & Jerry",
            "biDanh": "tom-jerry",
            "trailer": "https://www.youtube.com/watch?v=kP9TfCWaQT4",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tom-jerry_gp01.jpg",
            "moTa": "Tom & Jerry Battle",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6144,
            "tenPhim": "Tom & Jerry",
            "biDanh": "tom-jerry",
            "trailer": "https://www.youtube.com/watch?v=kP9TfCWaQT4",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tom-jerry_gp01.jpg",
            "moTa": "Tom & Jerry Battle",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6145,
            "tenPhim": "Tom & Jerry",
            "biDanh": "tom-jerry",
            "trailer": "https://www.youtube.com/watch?v=kP9TfCWaQT4",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/tom-jerry_gp01.jpg",
            "moTa": "Tom & Jerry Battle",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-30T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6146,
            "tenPhim": "Song Song",
            "biDanh": "song-song",
            "trailer": "youtube.com",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/song-song_gp01.jpg",
            "moTa": "Hay nha",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2021-04-12T19:34:51.267",
            "danhGia": 10
        },
        {
            "maPhim": 6150,
            "tenPhim": "Lật mặt",
            "biDanh": "lat-mat",
            "trailer": "https://www.youtube.com/watch?time_continue=1&v=UeyaR8jWl2c&feature=emb_title",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/lat-mat_gp01.jpg",
            "moTa": "Lật Mặt 5: 48H kể về Hiền - một cựu vận động viên võ thuật sau khi giải nghệ vì chấn thương đã cùng vợ và con gái về quê thăm gia đình Lâm. Họ bị cuốn vào một cuộc rượt đuổi với tay phản diện A Dìn. Để bảo vệ cho gia đình nhỏ, Hiền phải đưa vợ con chạy trốn khắp miền Tây sông nước với sự trợ giúp của người bạn thật thà và hài hước.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-05-20T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6153,
            "tenPhim": "lật mặt",
            "biDanh": "lat-mat",
            "trailer": "https://youtu.be/UeyaR8jWl2c",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/lat-mat_gp01.png",
            "moTa": "Lật Mặt 5: 48H kể về Hiền - một cựu vận động viên võ thuật sau khi giải nghệ vì chấn thương đã cùng vợ và con gái về quê thăm gia đình Lâm. Họ bị cuốn vào một cuộc rượt đuổi với tay phản diện A Dìn. Để bảo vệ cho gia đình nhỏ, Hiền phải đưa vợ con chạy trốn khắp miền Tây sông nước với sự trợ giúp của người bạn thật thà và hài hước.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-05-20T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6154,
            "tenPhim": "lật mặt",
            "biDanh": "lat-mat",
            "trailer": "https://www.youtube.com/watch?v=KlFh2oJzbfU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/lat-mat_gp01.png",
            "moTa": "Lật Mặt 5: 48H kể về Hiền - một cựu vận động viên võ thuật sau khi giải nghệ vì chấn thương đã cùng vợ và con gái về quê thăm gia đình Lâm. Họ bị cuốn vào một cuộc rượt đuổi với tay phản diện A Dìn. Để bảo vệ cho gia đình nhỏ, Hiền phải đưa vợ con chạy trốn khắp miền Tây sông nước với sự trợ giúp của người bạn thật thà và hài hước.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-05-20T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6155,
            "tenPhim": "lật mặt",
            "biDanh": "lat-mat",
            "trailer": "https://www.youtube.com/watch?v=twperjUjWRE",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/lat-mat_gp01.jpg",
            "moTa": "Lật Mặt 5: 48H kể về Hiền - một cựu vận động viên võ thuật sau khi giải nghệ vì chấn thương đã cùng vợ và con gái về quê thăm gia đình Lâm. Họ bị cuốn vào một cuộc rượt đuổi với tay phản diện A Dìn. Để bảo vệ cho gia đình nhỏ, Hiền phải đưa vợ con chạy trốn khắp miền Tây sông nước với sự trợ giúp của người bạn thật thà và hài hước.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        },
        {
            "maPhim": 6159,
            "tenPhim": "Godzilla vs. Kong",
            "biDanh": "godzilla-vs-kong",
            "trailer": "https://www.youtube.com/watch?v=KlFh2oJzbfU",
            "hinhAnh": "http://movie0706.cybersoft.edu.vn/hinhanh/godzilla-vs-kong_gp01.png",
            "moTa": "Khi hai kẻ thù truyền kiếp gặp nhau trong một trận chiến ngoạn mục, số phận của cả thế giới vẫn còn bị bỏ ngỏ… Bị đưa khỏi Đảo Đầu Lâu, Kong cùng Jia, một cô bé mồ côi có mối liên kết mạnh mẽ với mình và đội bảo vệ đặc biệt hướng về mái nhà mới. Bất ngờ, nhóm đụng độ phải Godzilla hùng mạnh, tạo ra một làn sóng hủy diệt trên toàn cầu. Thực chất, cuộc chiến giữa hai kẻ khổng lồ dưới sự thao túng của các thế lực vô hình mới chỉ là điểm khởi đầu để khám phá những bí ẩn nằm sâu trong tâm Trái đất.",
            "maNhom": "GP01",
            "ngayKhoiChieu": "2020-10-10T00:00:00",
            "danhGia": 10
        }
    ],
    chiTietPhim: {}
}
export const phimReducer = (state = stateDefault, action) => {
    switch (action.type) {
        case "SET_MANG_FILM": {
            // state.mangFilm = action.mangFilm;
            return { ...state, mangFilm: action.mangFilm }
        }
        case "SET_CHI_TIET_PHIM": {
            state.chiTietPhim = action.chiTietPhim;
            return { ...state }
        }
        default: return { ...state }
    }
}